### ISSUE TITLE
@supabase/ssr auth cookie is not set in OAuth flow in Next.js

### ISSUE THREAD

**Issue by ailon** [supabase/auth-helpers#661]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have created a brand-new project using `npx create-next-app -e with-supabase` starter. I verified that the built-in email auth flow works and changed it to use OAuth (in my case for Spotify, but I don't think that's important here) by following the docs pretty much to the letter.

The whole OAuth flow goes through as expected and a user is created in the database. However, unlike the email flow the `sb-localhost-auth-token` cookie is not set in the browser.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new Next.js with Supabase project using `npx create-next-app -e with-supabase`
2. Configure Supabase auth for an OAuth provider
3. Replace the login page with just a sign-in button
4. Replace sign-in route (`/app/auth/sign-in/route.ts`) with an OAuth flow:

```ts
import { createClient } from '@/utils/supabase/server'
import { NextResponse } from 'next/server'
import { cookies } from 'next/headers'

export async function POST(request: Request) {
  const requestUrl = new URL(request.url)
  const cookieStore = cookies()
  const supabase = createClient(cookieStore)

  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'spotify',
    options: {
      scopes: 'user-read-email',
      redirectTo: `${requestUrl.origin}/auth/callback`,
    },
  })

  return NextResponse.redirect(data.url ?? requestUrl.origin, {
    // a 301 status is required to redirect from a POST to a GET route
    status: 301,
  })
}
```
5. Replace callback route handler (`app/auth/callback/route.ts`) with an OAuth version:
```ts
import { createClient } from "@/utils/supabase/server";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const code = searchParams.get("code");
  const next = searchParams.get("next") ?? "/empty";

  if (code) {
    const cookieStore = cookies();

    const supabase = createClient(cookieStore);
    const { error } = await supabase.auth.exchangeCodeForSession(code);
    if (!error) {
      return NextResponse.redirect(new URL(`/${next.slice(1)}`, request.url));
    }
  }

  // return the user to an error page with instructions
  return NextResponse.redirect(
    new URL("/auth/auth-code-error", request.url)
  );
}
```
6. See that `sb-localhost-auth-token` cookie is not set.

## Expected behavior

Authentication cookie should be set.

## System information

- OS: Windows 11
- Browser (if applies) Chrome
- Version of supabase-js: 2.38.4
- Version of supabase/ssr: 0.0.4
- Version of Next.js: 14.0.0 (also tried with the latest 13.x with same result)
- Version of Node.js: 18.18.2

**Comment by ThomasLeveque** [comment]
Hey Alion !
I have the exact same issue:

After some research here https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts which is class that is extends by `SupabaseAuthClient` and where the function `exchangeCodeForSession` is. I found that inside `_exchangeCodeForSession` when we have a session return by the request, it should trigger `await this._saveSession(data.session)`. And it does ! because after i turn options.auth.debug to true inside `createServerClient` i can see this 👇 
![image](https://github.com/supabase/auth-helpers/assets/29226450/a9fd861a-fbe3-428b-83d6-b681fa69240a)
The log `#_persistSession() ...` is the line right before `setItemAsync` that should set the cookie.

Am i missing something ?

**Comment by ailon** [comment]
@ThomasLeveque idk, I just switched to `auth-helpers` for now and it works. Hoping someone smarter than me can see what's going on right away. Spent half a day hitting my head against the wall. 😅

**Comment by edwnjos** [comment]
I'm facing the same issue. The authentication part works, I can print the users email and access tokens on the callback route but the caching seems to be not working. 

I've also tested with the example on canary and the same issue happens. The authentication works but the auth button on the header doesn't change to "Hey, EMAIL!": https://github.com/vercel/next.js/tree/ee9a13aaa0592102e229bb3e5959cebe0a7a060c/examples/with-supabase

**Comment by silentworks** [comment]
This is likely due to the cookie size being larger than what you are allowed to save in the browser. We just released version 0.0.5 of the ssr package which has some cookie chunking methods in it but it will take a few days for us to get some guides out on how to use these. And this works in the `auth-helpers` because we shipped a version a few days ago that handles cookie chunking for you in it's code.

**Comment by ailon** [comment]
Thanks, @silentworks! Great to hear "it wasn't me" :) and that it's getting resolved.

Do I understand correctly that `auth-helpers` didn't work correctly with (some?) OAuth flows up until just recently? I'm just starting to explore supabase and this gives me pause.

**Comment by Gbuomprisco** [comment]
> Thanks, @silentworks! Great to hear "it wasn't me" :) and that it's getting resolved.
> 
> Do I understand correctly that `auth-helpers` didn't work correctly with (some?) OAuth flows up until just recently? I'm just starting to explore supabase and this gives me pause.

Is there any code we can look at to fix this in the meantime?

**Comment by Pbmangan** [comment]
This is troubling as it was just released in "next-auth-helpers" being deprecated and the new ssr package does not properly support Oath as found here. Upgrading to 0.0.5 did not solve for me.

**Comment by Gbuomprisco** [comment]
> This is likely due to the cookie size being larger than what you are allowed to save in the browser. We just released version 0.0.5 of the ssr package which has some cookie chunking methods in it but it will take a few days for us to get some guides out on how to use these. And this works in the `auth-helpers` because we shipped a version a few days ago that handles cookie chunking for you in it's code.

It's my understanding that the cookie chunking addition to make the library work will be a guide rather than a transparent addition to this library. Is that case? 

I have a working solution to this issue - but I am reluctant to add it's going to be handled by the library internally.

**Comment by Pbmangan** [comment]
I had to revert back to old auth packages. A bit frustrating given huge
amount of dev time to realize it was a package issue at the end when the
previous package was marked depreciated.

**Comment by LHDi** [comment]
Having the same issue with Discord login and Magic link, spent half of the day migrating just to find out that I can't log in anymore.
@Gbuomprisco can you please provide the solution you have 🙏

**Comment by silentworks** [comment]
We just released version 0.0.6 of the `@supabase/ssr` package which should address this. Please report back here if the issue has been resolved or if it's still unresolved for you.

**Comment by Alexandredc** [comment]
Hello there,

Still not working for me.
I notice that the token is now called : `sb-***-auth-token.1`

Maybe  the chunk 0 is missing ? 🤷🏻‍♂️

**Comment by Gbuomprisco** [comment]
I've updated and seems all good now!

**Comment by silentworks** [comment]
> Hello there,
> 
> Still not working for me. I notice that the token is now called : `sb-***-auth-token.1`
> 
> Maybe the chunk 0 is missing ? 🤷🏻‍♂️

Please create a minimal reproducible example for us to take a look at this. Yes there should be a `sb-***-auth-token.0` cookie too.

**Comment by Alexandredc** [comment]
I just figure out that `sb-***-auth-token.0` lenth is too long to be stored in cookie

Considering this code, I confirm that `sb-***-auth-token.0` is logged in the terminal
```ts
  const supabase = createServerClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          console.log(name);
          console.log(value);
          cookieStore.set({ name, value, ...options });
        },
        remove(name: string, options: CookieOptions) {
          cookieStore.set({ name, value: '', ...options });
        }
      }
    }
  );
```

I try with Google and Facebook provider

**Comment by Gbuomprisco** [comment]
> I just figure out that `sb-***-auth-token.0` lenth is too long to be stored in cookie
> 
> Considering this code, I confirm that `sb-***-auth-token.0` is logged in the terminal
> 
> ```ts
>   const supabase = createServerClient<Database>(
>     process.env.NEXT_PUBLIC_SUPABASE_URL!,
>     process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
>     {
>       cookies: {
>         get(name: string) {
>           return cookieStore.get(name)?.value;
>         },
>         set(name: string, value: string, options: CookieOptions) {
>           console.log(name);
>           console.log(value);
>           cookieStore.set({ name, value, ...options });
>         },
>         remove(name: string, options: CookieOptions) {
>           cookieStore.set({ name, value: '', ...options });
>         }
>       }
>     }
>   );
> ```
> 
> I try with Google and Facebook provider
> 
> Is it normal to have the whole session inside the cookie ? Before using `@supabase/ssr`, only the acces token was stored

I may have seen the same so I had decreased the max chunk size to 200 - @silentworks I wonder if the chunking can be smarter checking the bytes of string will not exceed 4096 bytes?

**Comment by silentworks** [comment]
@Alexandredc yes in the `ssr` package we are storing the whole session as the way how we were doing it in the auth-helpers required us to do base64 stuff in order to parse the cookie. This cookie is now storing the same information as `@supabase/supabase-js` does when using local storage. I think if this was to be reduced in the cookie then it should be done at the `gotrue-js` level rather than at the `ssr` package level, however I could be wrong here and this is just my own opinion.

**Comment by silentworks** [comment]
@Gbuomprisco we could probably calculate the entire string size along with the name, since name is counted towards the size of a cookie and then divide that into chunks that would be below the 4096 bytes limit. Another option is also to lock the name so it cannot be modified and also set it to a smaller sting to reduce the cookie size.

**Comment by Alexandredc** [comment]
@silentworks resolved with 0.0.7

Thanks for the quick update !

**Comment by ailon** [comment]
@silentworks works like charm for me in with 0.0.7. Thanks!

**Comment by dvvolynkin** [comment]
@silentworks 

I still have this issue for some of my users. Not for all. (ssr@^0.0.9)
The first chunk does not fit into the 4096. 

Trying to make a reproducible example

**Comment by jesuzon** [comment]
Just ran into this issue on 0.0.10 as well - only the sb-***-auth-token.1 is set, sb-***-auth-token.0 is missing.
inspecting the headers object in my callback route I can see that the headers are set correctly, but indeed the sb-***-auth-token.0 cookie looks too long, likely exceeding the browser limits.

I am using Remix if that's any help

**Comment by Gbuomprisco** [comment]
Some of my customers are also hitting this issue with some oAuth providers.

**Comment by jesuzon** [comment]
> Some of my customers are also hitting this issue with some oAuth providers.

Upon some inspection, I noticed that the dev server I was using (Remix with Vite 4.5) had a bug with multiple set-cookies or a set-cookie array in the header. I updated the Remix packages and things are working again.

Another thing to bear in mind is that your web server/dev server environment should support buffers that are greater than 4k, otherwise it can lead to server/gateway errors

**Comment by nullvana** [comment]
Please check if there are multiple identities for each provider. I discovered that my issue was due to having two identities, which exceeded the 4k limit.

**Comment by jj0b** [comment]
I'm still having this issue on supabase/ssr 0.1.0. 

I've followed the instructions to setup server-side auth for Next.js detailed here: https://supabase.com/docs/guides/auth/server-side/nextjs

In the `auth/confirm` route I can get the user (or the session) no problem:

```typescript
import { type NextRequest, NextResponse } from 'next/server';

import { createClient } from '@/utils/supabase/server';
import { type EmailOtpType } from '@supabase/supabase-js';

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const token_hash = searchParams.get('token_hash');
  const type = searchParams.get('type') as EmailOtpType | null;
  const next = searchParams.get('next') ?? '/';
  const redirectTo = request.nextUrl.clone();
  redirectTo.pathname = next;
  redirectTo.searchParams.delete('token_hash');
  redirectTo.searchParams.delete('type');

  if (token_hash && type) {
    const supabase = createClient();

    const { error } = await supabase.auth.verifyOtp({
      type,
      token_hash,
    });

    if (!error) {
      const {
        data: { user },
      } = await supabase.auth.getUser();

      console.log('USER: ', user);

      redirectTo.searchParams.delete('next');
      return NextResponse.redirect(redirectTo);
    }
  }

  // return the user to an error page with some instructions
  redirectTo.pathname = '/error';
  return NextResponse.redirect(redirectTo);
}
```

But I never see the cookie for the session show up in the inspector and then unsurprisingly, if I try to get the user or session in the middleware, or on a SSR page, doing things exactly as is shown in the docs I linked above, I always get null for the user or session and this error:

`AuthApiError: invalid claim: missing sub claim`

I assume this is because the cookie is never actually set.

Strangely, I do see the `sb-localhost-auth-token` cookie get set if I do a `supabase db reset`, `supabase stop`, and `supabase start` and then request a Magic Link. That first time this results in my having to confirm my email. When I follow the link to confirm my email, I can see the correct cookie in the inspector. As soon as I then make a second request for a Magic Link, resulting in the normal Magic Link email and link, when I follow that, the `sb-localhost-auth-token` gets removed.

**Comment by albertocubeddu** [comment]
I'm having the same issue, the cookie is magically disappearing when NextJS perform a redirect; 

`if ( token_hash && type )
    {
        const supabase = createClient()

        const { data, error } = await supabase.auth.verifyOtp( {
            type,
            token_hash
        } )

        console.log(data?.user?.id)

        const response = NextResponse.redirect(
            "http://localhost:3000/private",
            { status: 302 }
          );

          return response
}
`

However if i just return a json response 
`    if ( token_hash && type )
    {
        const supabase = createClient()

        const { data, error } = await supabase.auth.verifyOtp( {
            type,
            token_hash
        } )

        console.log(data?.user?.id)

        return NextResponse.json(data)
}`

the cookie is set and i can navigate to the /private page being authenticated.

**Comment by abualmagd** [comment]
still facing the same issues with   supabase/ssr 0.0.10

**Comment by alcaidio** [comment]
> Is it normal to have the whole session inside the cookie ? Before using `@supabase/ssr`, only the acces token was stored
@Alexandredc I think it's not a problem because we use it only server side.
